### ISSUE TITLE
Cannot connect to redis docker container

### ISSUE THREAD

**Issue by paschaldev** [oanhnn/docker-laravel-echo-server#4]
I have a redis container setup from `bitnami/redis:latest`, forwarded ports `6379` with the server up and running however, this echo server container fails to work. I get this error 

```
L A R A V E L  E C H O  S E R V E R

version 1.5.0

Starting server...

✔  Running at 0.0.0.0 on port 6001
✔  Listening for http events...
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis redis:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis redis:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis redis:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis redis:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis redis:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis redis:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis redis:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis redis:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
```

**Comment by paschaldev** [comment]
I was able to connect using the same --network flag for both
